# Generated by Django 5.2.7 on 2026-08-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderImage",
        ),
    ]
