# Generated by Django 5.2.7 on 2026-08-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_average_rating_product_review_count"),
        ("products", "0002_productimage"),
    ]

    operations = []
